/* CVS $Id: $ */
package com.epimorphics.govData.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from ../../../../../resources/vocabulary/boundary-change.ttl 
 * @author Auto-generated by schemagen on 24 Jun 2010 12:24 
 */
public class BOUNDARYCHANGE {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://statistics.data.gov.uk/def/boundary-change/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>TODO</p> */
    public static final Property boundaryChangeOrder = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/boundaryChangeOrder" );
    
    /** <p>TODO</p> */
    public static final Property changeYear = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/changeYear" );
    
    /** <p>TODO</p> */
    public static final Property entityCode = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/entityCode" );
    
    /** <p>TODO</p> */
    public static final Property operativeInterval = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/operativeInterval" );
    
    /** <p>TODO</p> */
    public static final Property originatingChangeOrder = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/originatingChangeOrder" );
    
    /** <p>TODO</p> */
    public static final Property precedingArea = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/precedingArea" );
    
    /** <p>TODO</p> */
    public static final Property recodedFromArea = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/recodedFromArea" );
    
    /** <p>TODO</p> */
    public static final Property recodedToArea = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/recodedToArea" );
    
    /** <p>TODO</p> */
    public static final Property resultedFrom = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/resultedFrom" );
    
    /** <p>TODO</p> */
    public static final Property resultingArea = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/resultingArea" );
    
    /** <p>TODO</p> */
    public static final Property sameAreaAs = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/sameAreaAs" );
    
    /** <p>TODO</p> */
    public static final Property standardCode = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/standardCode" );
    
    /** <p>TODO</p> */
    public static final Property succeedingArea = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/succeedingArea" );
    
    /** <p>TODO</p> */
    public static final Property terminatedArea = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/terminatedArea" );
    
    /** <p>TODO</p> */
    public static final Property terminatingChangeOrder = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/terminatingChangeOrder" );
    
    /** <p>wasChangedBy is an abstract property to express that an artifact was modified 
     *  by a process.</p>
     */
    public static final Property wasChangedBy = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/wasChangedBy" );
    
    /** <p>TODO</p> */
    public static final Property wasTerminatedBy = m_model.createProperty( "http://statistics.data.gov.uk/def/boundary-change/wasTerminatedBy" );
    
    /** <p>TODO</p> */
    public static final Resource BoundaryChange = m_model.createResource( "http://statistics.data.gov.uk/def/boundary-change/BoundaryChange" );
    
    /** <p>TODO</p> */
    public static final Resource BoundedArea = m_model.createResource( "http://statistics.data.gov.uk/def/boundary-change/BoundedArea" );
    
    /** <p>TODO</p> */
    public static final Resource ChangeEvent = m_model.createResource( "http://statistics.data.gov.uk/def/boundary-change/ChangeEvent" );
    
    /** <p>TODO</p> */
    public static final Resource RecodingChange = m_model.createResource( "http://statistics.data.gov.uk/def/boundary-change/RecodingChange" );
    
}
