/* CVS $UkId: $ */
package com.epimorphics.govData.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from ../../../../../resources/ontology/reference.n3 
 * @author Auto-generated by schemagen on 14 Feb 2010 23:35 
 */
public class DGU {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://reference.data.gov.uk/def/reference/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The common class for all the items in this URI set.</p> */
    public static final Property itemType = m_model.createProperty( "http://reference.data.gov.uk/def/reference/itemType" );
    
    /** <p>The status of the URI set or dataset.</p> */
    public static final Property status = m_model.createProperty( "http://reference.data.gov.uk/def/reference/status" );
    
    /** <p>The URI set that this resource is part of.</p> */
    public static final Property uriSet = m_model.createProperty( "http://reference.data.gov.uk/def/reference/uriSet" );
    
    /** <p>The status of of a URI set or dataset.</p> */
    public static final Resource Status = m_model.createResource( "http://reference.data.gov.uk/def/reference/Status" );
    
    /** <p>A collection of resources that are all the same kind of thing.</p> */
    public static final Resource URIset = m_model.createResource( "http://reference.data.gov.uk/def/reference/URIset" );
    
    public static final Resource draft = m_model.createResource( "http://reference.data.gov.uk/def/status/draft" );
    
    public static final Resource final_ = m_model.createResource( "http://reference.data.gov.uk/def/status/final" );
    
}
