/* CVS $Id: $ */
package com.epimorphics.govData.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from http://usefulinc.com/ns/doap 
 * @author Auto-generated by schemagen on 18 Feb 2010 09:34 
 */
public class DOAP {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://usefulinc.com/ns/doap#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>URL der Projekt-Homepage, verbunden mit genau einem Projekt.El URL de la página 
     *  de un proyecto, asociada con exactamente un proyecto.L'URL de la page web 
     *  d'un projet, associée avec un unique projet.URL adresa domovské stránky projektu 
     *  asociované s práv? jedním projektem.????????????????URL????????????????????????????????URL 
     *  of a project's homepage, associated with exactly one project.</p>
     */
    public static final ObjectProperty homepage = m_model.createObjectProperty( "http://usefulinc.com/ns/doap#homepage" );
    
    /** <p>URL adresa p?edešlé domovské stránky projektu asociované s práv? jedním projektem.??????????????????????????????????????????El 
     *  URL de la antigua página de un proyecto, asociada con exactamente un proyecto.URL 
     *  of a project's past homepage, associated with exactly one project.L'URL d'une 
     *  ancienne page web d'un projet, associée avec un unique projet.URL der letzten 
     *  Projekt-Homepage, verbunden mit genau einem Projekt.</p>
     */
    public static final ObjectProperty old_homepage = m_model.createObjectProperty( "http://usefulinc.com/ns/doap#old-homepage" );
    
    /** <p>????????????Repository für anonymen ZugriffRepository for anonymous access.Repositorio 
     *  para acceso anónimo.Dépôt pour accès anonyme.Úložišt? pro anonymní p?ístup.</p>
     */
    public static final OntProperty anon_root = m_model.createOntProperty( "http://usefulinc.com/ns/doap#anon-root" );
    
    /** <p>????????????Description of target user base</p> */
    public static final OntProperty audience = m_model.createOntProperty( "http://usefulinc.com/ns/doap#audience" );
    
    /** <p>????????????????URIURI of a blog related to a project</p> */
    public static final OntProperty blog = m_model.createOntProperty( "http://usefulinc.com/ns/doap#blog" );
    
    /** <p>??????????????????????????Webové rozhraní pro prohlížení úložišt?.Web browser 
     *  interface to repository.Web-Browser Interface für das Repository.Interface 
     *  web del repositorio.Interface web au dépôt.</p>
     */
    public static final OntProperty browse = m_model.createOntProperty( "http://usefulinc.com/ns/doap#browse" );
    
    /** <p>Suivi des bugs pour un projet.Bug tracker para un proyecto.Správa chyb projektu.Fehlerdatenbank 
     *  eines Projektes.???????????????Bug tracker for a project.</p>
     */
    public static final OntProperty bug_database = m_model.createOntProperty( "http://usefulinc.com/ns/doap#bug-database" );
    
    /** <p>A category of project.Eine Kategorie eines Projektes.Una categoría de proyecto.Une 
     *  catégorie de projet.????????????Kategorie projektu.</p>
     */
    public static final OntProperty category = m_model.createOntProperty( "http://usefulinc.com/ns/doap#category" );
    
    /** <p>Fecha en la que algo fue creado, en formato AAAA-MM-DD. e.g. 2004-04-05Erstellungsdatum 
     *  von Irgendwas, angegeben im YYYY-MM-DD Format, z.B. 2004-04-05.Date à laquelle 
     *  a été créé quelque chose, au format AAAA-MM-JJ (par ex. 2004-04-05)???????????AAAA-MM-JJ??????2004-04-05?Datum, 
     *  kdy bylo n?co vytvo?eno ve formátu RRRR-MM-DD, nap?. 2004-04-05Date when something 
     *  was created, in YYYY-MM-DD form. e.g. 2004-04-05</p>
     */
    public static final OntProperty created = m_model.createOntProperty( "http://usefulinc.com/ns/doap#created" );
    
    /** <p>?ist? textový, 2 až 4 v?ty dlouhý popis projektu.Descripción en texto plano 
     *  de un proyecto, de 2 a 4 enunciados de longitud.????????????2??4??????Texte 
     *  descriptif d'un projet, long de 2 à 4 phrases.Plain text description of a 
     *  project, of 2-4 sentences in length.Beschreibung eines Projekts als einfacher 
     *  Text mit der Länge von 2 bis 4 Sätzen.</p>
     */
    public static final OntProperty description = m_model.createOntProperty( "http://usefulinc.com/ns/doap#description" );
    
    /** <p>Developer of software for the project.?????????????????Développeur pour le 
     *  projet.Software-Entwickler für eine Projekt.Vývojá? softwaru projektu.Desarrollador 
     *  de software para el proyecto.</p>
     */
    public static final OntProperty developer = m_model.createOntProperty( "http://usefulinc.com/ns/doap#developer" );
    
    /** <p>Proveedor de documentación para el proyecto.???????????????????Spoluautor 
     *  dokumentace projektu.Contributor of documentation to the project.Mitarbeiter 
     *  an der Dokumentation eines Projektes.Collaborateur à la documentation du projet.</p>
     */
    public static final OntProperty documenter = m_model.createOntProperty( "http://usefulinc.com/ns/doap#documenter" );
    
    /** <p>??????????????????Miroir de la page de téléchargement du programme.Spiegel 
     *  der Seite von die Projekt-Software heruntergeladen werden kann.Mirror de la 
     *  página web de descarga.Mirror of software download web page.Zrcadlo stránky 
     *  pro stažení softwaru.</p>
     */
    public static final OntProperty download_mirror = m_model.createOntProperty( "http://usefulinc.com/ns/doap#download-mirror" );
    
    /** <p>Page web à partir de laquelle on peut télécharger le programme.Página web 
     *  de la cuál se puede bajar el software.Web page from which the project software 
     *  can be downloaded.Web-Seite von der die Projekt-Software heruntergeladen werden 
     *  kann.Webová stránka, na které lze stáhnout projektový software.????????????????????????</p>
     */
    public static final OntProperty download_page = m_model.createOntProperty( "http://usefulinc.com/ns/doap#download-page" );
    
    /** <p>URI adresa stažení asociované s revizí.URI of download associated with this 
     *  release.</p>
     */
    public static final OntProperty file_release = m_model.createOntProperty( "http://usefulinc.com/ns/doap#file-release" );
    
    /** <p>Colaborador del proyecto.Projekt-Mitarbeiter.Project contributor.Spoluautor 
     *  projektu.????????????Collaborateur au projet.</p>
     */
    public static final OntProperty helper = m_model.createOntProperty( "http://usefulinc.com/ns/doap#helper" );
    
    /** <p>?????????????????????????API???????????A specification that a project implements. 
     *  Could be a standard, API or legally defined level of conformance.</p>
     */
    public static final OntProperty implements_ = m_model.createOntProperty( "http://usefulinc.com/ns/doap#implements" );
    
    /** <p>?????????????????ISO?????ISO language code a project has been translated into</p> */
    public static final OntProperty language = m_model.createOntProperty( "http://usefulinc.com/ns/doap#language" );
    
    /** <p>Die URI einer RDF-Beschreibung einer Lizenz unter der die Software herausgegeben 
     *  wird.El URI de una descripción RDF de la licencia bajo la cuál se distribuye 
     *  el software.The URI of an RDF description of the license the software is distributed 
     *  under.URI adresa RDF popisu licence, pod kterou je software distribuován.?????????????????RDF???URIL'URI 
     *  d'une description RDF de la licence sous laquelle le programme est distribué.</p>
     */
    public static final OntProperty license = m_model.createOntProperty( "http://usefulinc.com/ns/doap#license" );
    
    /** <p>Lokation eines Repositorys.???????????Emplacement d'un dépôt.Location of a 
     *  repository.lugar de un repositorio.Umíst?ní úložišt?.</p>
     */
    public static final OntProperty location = m_model.createOntProperty( "http://usefulinc.com/ns/doap#location" );
    
    /** <p>Mailing list home page or email address.???????????????????????Homepage der 
     *  Mailing Liste oder E-Mail Adresse.Page web de la liste de diffusion, ou adresse 
     *  de courriel.Domovská stránka nebo e–mailová adresa e–mailové diskuse.Página 
     *  web de la lista de correo o dirección de correo.</p>
     */
    public static final OntProperty mailing_list = m_model.createOntProperty( "http://usefulinc.com/ns/doap#mailing-list" );
    
    /** <p>Hauptentwickler eines Projektes, der ProjektleiterSprávce projektu, vedoucí 
     *  projektu.????????????????????Développeur principal d'un projet, un meneur 
     *  du projet.Maintainer of a project, a project leader.Desarrollador principal 
     *  de un proyecto, un líder de proyecto.</p>
     */
    public static final OntProperty maintainer = m_model.createOntProperty( "http://usefulinc.com/ns/doap#maintainer" );
    
    /** <p>Nom du module d'un dépôt.Jméno modulu v úložišti.Nombre del módulo de un repositorio.Module 
     *  name of a repository.Modul-Name eines Subversion.???????????????</p>
     */
    public static final OntProperty module = m_model.createOntProperty( "http://usefulinc.com/ns/doap#module" );
    
    /** <p>Der Name von IrgendwasJméno n??eho.A name of something.?????El nombre de algo.Le 
     *  nom de quelque chose.</p>
     */
    public static final OntProperty name = m_model.createOntProperty( "http://usefulinc.com/ns/doap#name" );
    
    /** <p>Operating system that a project is limited to. Omit this property if the project 
     *  is not OS-specific.Sistema opertivo al cuál está limitado el proyecto. Omita 
     *  esta propiedad si el proyecto no es específico de un sistema opertaivo en 
     *  particular.Opera?ní systém, na jehož použití je projekt limitován. Vynechejte 
     *  tuto vlastnost, pokud je projekt nezávislý na opera?ním systému.Système d'exploitation 
     *  auquel est limité le projet. Omettez cette propriété si le projet n'est pas 
     *  limité à un système d'exploitation.??????????????????????????????????????OS????????????????????????Betriebssystem 
     *  auf dem das Projekt eingesetzt werden kann. Diese Eigenschaft kann ausgelassen 
     *  werden, wenn das Projekt nicht BS-spezifisch ist.</p>
     */
    public static final OntProperty os = m_model.createOntProperty( "http://usefulinc.com/ns/doap#os" );
    
    /** <p>Indicator of software platform (non-OS specific), e.g. Java, Firefox, ECMA 
     *  CLR?????????????????????OS???????????Java?Firefox?ECMA CLR???</p>
     */
    public static final OntProperty platform = m_model.createOntProperty( "http://usefulinc.com/ns/doap#platform" );
    
    /** <p>?????????????????????????????????Lenguaje de programación en el que un proyecto 
     *  es implementado o con el cuál pretende usarse.Programming language a project 
     *  is implemented in or intended for use with.Programmiersprache in der ein Projekt 
     *  implementiert ist oder intendiert wird zu benutzen.Langage de programmation 
     *  avec lequel un projet est implémenté, ou avec lequel il est prévu de l'utiliser.Programovací 
     *  jazyk, ve kterém je projekt implementován nebo pro který je zamýšlen k použití.</p>
     */
    public static final OntProperty programming_language = m_model.createOntProperty( "http://usefulinc.com/ns/doap#programming-language" );
    
    /** <p>Une release (révision) d'un projet.Relase (verze) projektu.A project release.Un 
     *  release (versión) de un proyecto.?????????????Ein Release (Version) eines 
     *  Projekts.</p>
     */
    public static final OntProperty release = m_model.createOntProperty( "http://usefulinc.com/ns/doap#release" );
    
    /** <p>Úložišt? zdrojových kód?.Quellcode-Versionierungssystem.Dépôt du code source.?????????????????????Source 
     *  code repository.Repositorio del código fuente.</p>
     */
    public static final OntProperty repository = m_model.createOntProperty( "http://usefulinc.com/ns/doap#repository" );
    
    /** <p>Indentificador de la versión de un release de software.???????????????Versionsidentifikator 
     *  eines Software-Releases.Identifiant de révision d'une release du programme.Revision 
     *  identifier of a software release.Identifikátor zp?ístupn?né revize softwaru.</p>
     */
    public static final OntProperty revision = m_model.createOntProperty( "http://usefulinc.com/ns/doap#revision" );
    
    /** <p>Webová stránka projektu se snímky obrazovky.Web-Seite mit Screenshots eines 
     *  Projektes.Page web avec des captures d'écran du projet.Web page with screenshots 
     *  of project.Página web con capturas de pantalla del proyecto.??????????????????</p>
     */
    public static final OntProperty screenshots = m_model.createOntProperty( "http://usefulinc.com/ns/doap#screenshots" );
    
    /** <p>?????????????????????????The URI of a web service endpoint where software 
     *  as a service may be accessed</p>
     */
    public static final OntProperty service_endpoint = m_model.createOntProperty( "http://usefulinc.com/ns/doap#service-endpoint" );
    
    /** <p>Krátký (8 nebo 9 slov) ?ist? textový popis projektu.Short (8 or 9 words) plain 
     *  text description of a project.Descripción corta (8 o 9 palabras) en texto 
     *  plano de un proyecto.Texte descriptif concis (8 ou 9 mots) d'un projet.Kurzbeschreibung 
     *  (8 oder 9 Wörter) eines Projects als einfacher Text.??????????????</p>
     */
    public static final OntProperty shortdesc = m_model.createOntProperty( "http://usefulinc.com/ns/doap#shortdesc" );
    
    /** <p>Un tester u otro proveedor de control de calidad.Tester nebo jiný spoluautor 
     *  kontrolující kvalitu.Un testeur ou un collaborateur au contrôle qualité.Ein 
     *  Tester oder anderer Mitarbeiter der Qualitätskontrolle.A tester or other quality 
     *  control contributor.???????????????????????????</p>
     */
    public static final OntProperty tester = m_model.createOntProperty( "http://usefulinc.com/ns/doap#tester" );
    
    /** <p>????????????????Spoluautor p?ekladu projektu.Proveedor de traducciones al 
     *  proyecto.Collaborateur à la traduction du projet.Contributor of translations 
     *  to the project.Mitarbeiter an den Übersetzungen eines Projektes.</p>
     */
    public static final OntProperty translator = m_model.createOntProperty( "http://usefulinc.com/ns/doap#translator" );
    
    /** <p>?????????????????Vendor organization: commercial, free or otherwise</p> */
    public static final OntProperty vendor = m_model.createOntProperty( "http://usefulinc.com/ns/doap#vendor" );
    
    /** <p>URL of Wiki for collaborative discussion of project.???????????????L'URL du 
     *  Wiki pour la discussion collaborative sur le projet.URL del Wiki para discusión 
     *  colaborativa del proyecto.Wiki-URL für die kollaborative Dikussion eines Projektes.URL 
     *  adresa wiki projektu pro spole?né diskuse.</p>
     */
    public static final OntProperty wiki = m_model.createOntProperty( "http://usefulinc.com/ns/doap#wiki" );
    
    /** <p>GNU Arch Quellcode-Versionierungssystem.Dépôt GNU Arch du code source.GNU 
     *  Arch source code repository.Repositorio GNU Arch del código fuente.???????GNU 
     *  Arch??????Úložišt? zdrojových kód? GNU Arch.</p>
     */
    public static final OntClass ArchRepository = m_model.createClass( "http://usefulinc.com/ns/doap#ArchRepository" );
    
    /** <p>Dépôt BitKeeper du code source.Úložišt? zdrojových kód? BitKeeper.BitKeeper 
     *  Quellcode-Versionierungssystem.???????BitKeeper??????Repositorio BitKeeper 
     *  del código fuente.BitKeeper source code repository.</p>
     */
    public static final OntClass BKRepository = m_model.createClass( "http://usefulinc.com/ns/doap#BKRepository" );
    
    /** <p>Bazaar source code branch.???????Bazzar??????</p> */
    public static final OntClass BazaarBranch = m_model.createClass( "http://usefulinc.com/ns/doap#BazaarBranch" );
    
    /** <p>CVS source code repository.Úložišt? zdrojových kód? CVS.Repositorio CVS del 
     *  código fuente.CVS Quellcode-Versionierungssystem.???????CVS??????Dépôt CVS 
     *  du code source.</p>
     */
    public static final OntClass CVSRepository = m_model.createClass( "http://usefulinc.com/ns/doap#CVSRepository" );
    
    /** <p>Dépôt darcs du code source.???????darcs??????darcs source code repository.Repositorio 
     *  darcs del código fuente.</p>
     */
    public static final OntClass DarcsRepository = m_model.createClass( "http://usefulinc.com/ns/doap#DarcsRepository" );
    
    /** <p>Repositorio Git del código fuente.Úložišt? zdrojových kód? Git.Dépôt Git du 
     *  code source.Git source code repository.???????Git??????Git Quellcode-Versionierungssystem.</p>
     */
    public static final OntClass GitRepository = m_model.createClass( "http://usefulinc.com/ns/doap#GitRepository" );
    
    /** <p>Mercurial source code repository.???????Mercurial??????</p> */
    public static final OntClass HgRepository = m_model.createClass( "http://usefulinc.com/ns/doap#HgRepository" );
    
    /** <p>??????????????Ein Projekt.Projekt.A project.Un proyecto.Un projet.</p> */
    public static final OntClass Project = m_model.createClass( "http://usefulinc.com/ns/doap#Project" );
    
    /** <p>Úložišt? zdrojových kód?.Quellcode-Versionierungssystem.Dépôt du code source.Source 
     *  code repository.????????????Repositorio del código fuente.</p>
     */
    public static final OntClass Repository = m_model.createClass( "http://usefulinc.com/ns/doap#Repository" );
    
    /** <p>Dépôt Subversion du code source.Úložišt? zdrojových kód? Subversion.???????Subversion??????Subversion 
     *  Quellcode-Versionierungssystem.Subversion source code repository.Repositorio 
     *  Subversion del código fuente.</p>
     */
    public static final OntClass SVNRepository = m_model.createClass( "http://usefulinc.com/ns/doap#SVNRepository" );
    
    /** <p>??????????????????????????A specification of a system's aspects, technical 
     *  or otherwise.</p>
     */
    public static final OntClass Specification = m_model.createClass( "http://usefulinc.com/ns/doap#Specification" );
    
    /** <p>Versionsinformation eines Projekt Releases.Informace o uvoln?né verzi projektu.????????????Détails 
     *  sur une version d'une realease d'un projet.Información sobre la versión de 
     *  un release del proyecto.Version information of a project release.</p>
     */
    public static final OntClass Version = m_model.createClass( "http://usefulinc.com/ns/doap#Version" );
    
}
