/* CVS $Id: $ */
package com.epimorphics.govData.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://usefulinc.com/ns/doap 
 * @author Auto-generated by schemagen on 08 Dec 2010 14:09 
 */
public class DOAP {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://usefulinc.com/ns/doap#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>匿名でアクセスできるパスRepository für anonymen ZugriffRepository for anonymous access.Repositorio 
     *  para acceso anónimo.Dépôt pour accès anonyme.Úložiště pro anonymní přístup.</p>
     */
    public static final Property anon_root = m_model.createProperty( "http://usefulinc.com/ns/doap#anon-root" );
    
    /** <p>目指したユーザたちの説明Description of target user base</p> */
    public static final Property audience = m_model.createProperty( "http://usefulinc.com/ns/doap#audience" );
    
    /** <p>このプロジェクトに関するブログのURIURI of a blog related to a project</p> */
    public static final Property blog = m_model.createProperty( "http://usefulinc.com/ns/doap#blog" );
    
    /** <p>このリポジトリのウェブのウェブのユーザインタフェースWebové rozhraní pro prohlížení úložiště.Web browser 
     *  interface to repository.Web-Browser Interface für das Repository.Interface 
     *  web del repositorio.Interface web au dépôt.</p>
     */
    public static final Property browse = m_model.createProperty( "http://usefulinc.com/ns/doap#browse" );
    
    /** <p>Suivi des bugs pour un projet.Bug tracker para un proyecto.Správa chyb projektu.Fehlerdatenbank 
     *  eines Projektes.このプロジェクのバグ管理ページBug tracker for a project.</p>
     */
    public static final Property bug_database = m_model.createProperty( "http://usefulinc.com/ns/doap#bug-database" );
    
    /** <p>A category of project.Eine Kategorie eines Projektes.Una categoría de proyecto.Une 
     *  catégorie de projet.このプロジェクトの分類。Kategorie projektu.</p>
     */
    public static final Property category = m_model.createProperty( "http://usefulinc.com/ns/doap#category" );
    
    /** <p>Fecha en la que algo fue creado, en formato AAAA-MM-DD. e.g. 2004-04-05Erstellungsdatum 
     *  von Irgendwas, angegeben im YYYY-MM-DD Format, z.B. 2004-04-05.Date à laquelle 
     *  a été créé quelque chose, au format AAAA-MM-JJ (par ex. 2004-04-05)何かが作成された日付、AAAA-MM-JJの型、例えば2004-04-05。Datum, 
     *  kdy bylo něco vytvořeno ve formátu RRRR-MM-DD, např. 2004-04-05Date when something 
     *  was created, in YYYY-MM-DD form. e.g. 2004-04-05</p>
     */
    public static final Property created = m_model.createProperty( "http://usefulinc.com/ns/doap#created" );
    
    /** <p>Čistě textový, 2 až 4 věty dlouhý popis projektu.Descripción en texto plano 
     *  de un proyecto, de 2 a 4 enunciados de longitud.プロジェクトの文の説明、2から4までの行数。Texte 
     *  descriptif d'un projet, long de 2 à 4 phrases.Plain text description of a 
     *  project, of 2-4 sentences in length.Beschreibung eines Projekts als einfacher 
     *  Text mit der Länge von 2 bis 4 Sätzen.</p>
     */
    public static final Property description = m_model.createProperty( "http://usefulinc.com/ns/doap#description" );
    
    /** <p>Developer of software for the project.プロジェクトのソフトウェアの開発者Développeur pour le 
     *  projet.Software-Entwickler für eine Projekt.Vývojář softwaru projektu.Desarrollador 
     *  de software para el proyecto.</p>
     */
    public static final Property developer = m_model.createProperty( "http://usefulinc.com/ns/doap#developer" );
    
    /** <p>Proveedor de documentación para el proyecto.このプロジェクトのドキュメントの貢献者Spoluautor 
     *  dokumentace projektu.Contributor of documentation to the project.Mitarbeiter 
     *  an der Dokumentation eines Projektes.Collaborateur à la documentation du projet.</p>
     */
    public static final Property documenter = m_model.createProperty( "http://usefulinc.com/ns/doap#documenter" );
    
    /** <p>このプロジェクトのダウンロードミラーMiroir de la page de téléchargement du programme.Spiegel 
     *  der Seite von die Projekt-Software heruntergeladen werden kann.Mirror de la 
     *  página web de descarga.Mirror of software download web page.Zrcadlo stránky 
     *  pro stažení softwaru.</p>
     */
    public static final Property download_mirror = m_model.createProperty( "http://usefulinc.com/ns/doap#download-mirror" );
    
    /** <p>Page web à partir de laquelle on peut télécharger le programme.Página web 
     *  de la cuál se puede bajar el software.Web page from which the project software 
     *  can be downloaded.Web-Seite von der die Projekt-Software heruntergeladen werden 
     *  kann.Webová stránka, na které lze stáhnout projektový software.このプロジェクトのダウンロードできるウェブページ</p>
     */
    public static final Property download_page = m_model.createProperty( "http://usefulinc.com/ns/doap#download-page" );
    
    /** <p>URI adresa stažení asociované s revizí.URI of download associated with this 
     *  release.</p>
     */
    public static final Property file_release = m_model.createProperty( "http://usefulinc.com/ns/doap#file-release" );
    
    /** <p>Colaborador del proyecto.Projekt-Mitarbeiter.Project contributor.Spoluautor 
     *  projektu.このプロジェクトの貢献者Collaborateur au projet.</p>
     */
    public static final Property helper = m_model.createProperty( "http://usefulinc.com/ns/doap#helper" );
    
    /** <p>URL der Projekt-Homepage, verbunden mit genau einem Projekt.El URL de la página 
     *  de un proyecto, asociada con exactamente un proyecto.L'URL de la page web 
     *  d'un projet, associée avec un unique projet.URL adresa domovské stránky projektu 
     *  asociované s právě jedním projektem.このプロジェクトのホームページのURL。このホームページは他のプロジェクトのホームページじゃないこと。URL 
     *  of a project's homepage, associated with exactly one project.</p>
     */
    public static final Property homepage = m_model.createProperty( "http://usefulinc.com/ns/doap#homepage" );
    
    /** <p>このプロジェクトが実装したシステムの明細書。標準やAPIや明細書のようなもの。A specification that a project implements. 
     *  Could be a standard, API or legally defined level of conformance.</p>
     */
    public static final Property implements_ = m_model.createProperty( "http://usefulinc.com/ns/doap#implements" );
    
    /** <p>このプロジェクトの翻訳された言語のISO言語コートISO language code a project has been translated into</p> */
    public static final Property language = m_model.createProperty( "http://usefulinc.com/ns/doap#language" );
    
    /** <p>Die URI einer RDF-Beschreibung einer Lizenz unter der die Software herausgegeben 
     *  wird.El URI de una descripción RDF de la licencia bajo la cuál se distribuye 
     *  el software.The URI of an RDF description of the license the software is distributed 
     *  under.URI adresa RDF popisu licence, pod kterou je software distribuován.このプロジェクトの散布ライセンスのRDF説明のURIL'URI 
     *  d'une description RDF de la licence sous laquelle le programme est distribué.</p>
     */
    public static final Property license = m_model.createProperty( "http://usefulinc.com/ns/doap#license" );
    
    /** <p>Lokation eines Repositorys.このリポジトリの場所。Emplacement d'un dépôt.Location of a 
     *  repository.lugar de un repositorio.Umístění úložiště.</p>
     */
    public static final Property location = m_model.createProperty( "http://usefulinc.com/ns/doap#location" );
    
    /** <p>Mailing list home page or email address.メーリングリストのホームページやメールアドレスHomepage der 
     *  Mailing Liste oder E-Mail Adresse.Page web de la liste de diffusion, ou adresse 
     *  de courriel.Domovská stránka nebo e–mailová adresa e–mailové diskuse.Página 
     *  web de la lista de correo o dirección de correo.</p>
     */
    public static final Property mailing_list = m_model.createProperty( "http://usefulinc.com/ns/doap#mailing-list" );
    
    /** <p>Hauptentwickler eines Projektes, der ProjektleiterSprávce projektu, vedoucí 
     *  projektu.このプロジェクトのメンテなー及びリーダ。Développeur principal d'un projet, un meneur 
     *  du projet.Maintainer of a project, a project leader.Desarrollador principal 
     *  de un proyecto, un líder de proyecto.</p>
     */
    public static final Property maintainer = m_model.createProperty( "http://usefulinc.com/ns/doap#maintainer" );
    
    /** <p>Nom du module d'un dépôt.Jméno modulu v úložišti.Nombre del módulo de un repositorio.Module 
     *  name of a repository.Modul-Name eines Subversion.このリポジトリのモジュール名前</p>
     */
    public static final Property module = m_model.createProperty( "http://usefulinc.com/ns/doap#module" );
    
    /** <p>Der Name von IrgendwasJméno něčeho.A name of something.何かの名前El nombre de algo.Le 
     *  nom de quelque chose.</p>
     */
    public static final Property name = m_model.createProperty( "http://usefulinc.com/ns/doap#name" );
    
    /** <p>URL adresa předešlé domovské stránky projektu asociované s právě jedním projektem.このプロジェクトの前のホームページ。他のプロジェクトの前のホームページじゃないこと。El 
     *  URL de la antigua página de un proyecto, asociada con exactamente un proyecto.URL 
     *  of a project's past homepage, associated with exactly one project.L'URL d'une 
     *  ancienne page web d'un projet, associée avec un unique projet.URL der letzten 
     *  Projekt-Homepage, verbunden mit genau einem Projekt.</p>
     */
    public static final Property old_homepage = m_model.createProperty( "http://usefulinc.com/ns/doap#old-homepage" );
    
    /** <p>Operating system that a project is limited to. Omit this property if the project 
     *  is not OS-specific.Sistema opertivo al cuál está limitado el proyecto. Omita 
     *  esta propiedad si el proyecto no es específico de un sistema opertaivo en 
     *  particular.Operační systém, na jehož použití je projekt limitován. Vynechejte 
     *  tuto vlastnost, pokud je projekt nezávislý na operačním systému.Système d'exploitation 
     *  auquel est limité le projet. Omettez cette propriété si le projet n'est pas 
     *  limité à un système d'exploitation.このプロジェクトの限られたオペレーティングシステム。もし、プロジェクトはどのOSも大丈夫なら、このプロパティを書き落としていい。Betriebssystem 
     *  auf dem das Projekt eingesetzt werden kann. Diese Eigenschaft kann ausgelassen 
     *  werden, wenn das Projekt nicht BS-spezifisch ist.</p>
     */
    public static final Property os = m_model.createProperty( "http://usefulinc.com/ns/doap#os" );
    
    /** <p>Indicator of software platform (non-OS specific), e.g. Java, Firefox, ECMA 
     *  CLRこのプロジェクトの必要なプラットフォーム（OSに関係ない）。例えば：Java、Firefox、ECMA CLRとか。</p>
     */
    public static final Property platform = m_model.createProperty( "http://usefulinc.com/ns/doap#platform" );
    
    /** <p>このプログラミングの実装のプログラミング言語、または目指した言語。Lenguaje de programación en el que un proyecto 
     *  es implementado o con el cuál pretende usarse.Programming language a project 
     *  is implemented in or intended for use with.Programmiersprache in der ein Projekt 
     *  implementiert ist oder intendiert wird zu benutzen.Langage de programmation 
     *  avec lequel un projet est implémenté, ou avec lequel il est prévu de l'utiliser.Programovací 
     *  jazyk, ve kterém je projekt implementován nebo pro který je zamýšlen k použití.</p>
     */
    public static final Property programming_language = m_model.createProperty( "http://usefulinc.com/ns/doap#programming-language" );
    
    /** <p>Une release (révision) d'un projet.Relase (verze) projektu.A project release.Un 
     *  release (versión) de un proyecto.このプロジェクトのリリースEin Release (Version) eines 
     *  Projekts.</p>
     */
    public static final Property release = m_model.createProperty( "http://usefulinc.com/ns/doap#release" );
    
    /** <p>Úložiště zdrojových kódů.Quellcode-Versionierungssystem.Dépôt du code source.このプロジェクトのソースコードのリポジトリSource 
     *  code repository.Repositorio del código fuente.</p>
     */
    public static final Property repository = m_model.createProperty( "http://usefulinc.com/ns/doap#repository" );
    
    /** <p>Indentificador de la versión de un release de software.このリリースのリビジョン識別子Versionsidentifikator 
     *  eines Software-Releases.Identifiant de révision d'une release du programme.Revision 
     *  identifier of a software release.Identifikátor zpřístupněné revize softwaru.</p>
     */
    public static final Property revision = m_model.createProperty( "http://usefulinc.com/ns/doap#revision" );
    
    /** <p>Webová stránka projektu se snímky obrazovky.Web-Seite mit Screenshots eines 
     *  Projektes.Page web avec des captures d'écran du projet.Web page with screenshots 
     *  of project.Página web con capturas de pantalla del proyecto.スクリーンショットのあるウェブページ</p>
     */
    public static final Property screenshots = m_model.createProperty( "http://usefulinc.com/ns/doap#screenshots" );
    
    /** <p>ことプロジェクトが提供したサーブスを載せるサイト。The URI of a web service endpoint where software 
     *  as a service may be accessed</p>
     */
    public static final Property service_endpoint = m_model.createProperty( "http://usefulinc.com/ns/doap#service-endpoint" );
    
    /** <p>Krátký (8 nebo 9 slov) čistě textový popis projektu.Short (8 or 9 words) plain 
     *  text description of a project.Descripción corta (8 o 9 palabras) en texto 
     *  plano de un proyecto.Texte descriptif concis (8 ou 9 mots) d'un projet.Kurzbeschreibung 
     *  (8 oder 9 Wörter) eines Projects als einfacher Text.日本語の二十文字ぐらいの説明</p>
     */
    public static final Property shortdesc = m_model.createProperty( "http://usefulinc.com/ns/doap#shortdesc" );
    
    /** <p>Un tester u otro proveedor de control de calidad.Tester nebo jiný spoluautor 
     *  kontrolující kvalitu.Un testeur ou un collaborateur au contrôle qualité.Ein 
     *  Tester oder anderer Mitarbeiter der Qualitätskontrolle.A tester or other quality 
     *  control contributor.このプロジェクトのため、試験をする人や品質メンテナー。</p>
     */
    public static final Property tester = m_model.createProperty( "http://usefulinc.com/ns/doap#tester" );
    
    /** <p>このプロジェクトを翻訳する貢献者Spoluautor překladu projektu.Proveedor de traducciones al 
     *  proyecto.Collaborateur à la traduction du projet.Contributor of translations 
     *  to the project.Mitarbeiter an den Übersetzungen eines Projektes.</p>
     */
    public static final Property translator = m_model.createProperty( "http://usefulinc.com/ns/doap#translator" );
    
    /** <p>提供組織、商業の組織や自由の組織。Vendor organization: commercial, free or otherwise</p> */
    public static final Property vendor = m_model.createProperty( "http://usefulinc.com/ns/doap#vendor" );
    
    /** <p>URL of Wiki for collaborative discussion of project.このプロジェクトの討論用ウィキL'URL du 
     *  Wiki pour la discussion collaborative sur le projet.URL del Wiki para discusión 
     *  colaborativa del proyecto.Wiki-URL für die kollaborative Dikussion eines Projektes.URL 
     *  adresa wiki projektu pro společné diskuse.</p>
     */
    public static final Property wiki = m_model.createProperty( "http://usefulinc.com/ns/doap#wiki" );
    
    /** <p>GNU Arch Quellcode-Versionierungssystem.Dépôt GNU Arch du code source.GNU 
     *  Arch source code repository.Repositorio GNU Arch del código fuente.ソースコードのGNU 
     *  ArchのリポジトリÚložiště zdrojových kódů GNU Arch.</p>
     */
    public static final Resource ArchRepository = m_model.createResource( "http://usefulinc.com/ns/doap#ArchRepository" );
    
    /** <p>Dépôt BitKeeper du code source.Úložiště zdrojových kódů BitKeeper.BitKeeper 
     *  Quellcode-Versionierungssystem.ソースコードのBitKeeperのリポジトリRepositorio BitKeeper 
     *  del código fuente.BitKeeper source code repository.</p>
     */
    public static final Resource BKRepository = m_model.createResource( "http://usefulinc.com/ns/doap#BKRepository" );
    
    /** <p>Bazaar source code branch.ソースコードのBazzarのリポジトリ</p> */
    public static final Resource BazaarBranch = m_model.createResource( "http://usefulinc.com/ns/doap#BazaarBranch" );
    
    /** <p>CVS source code repository.Úložiště zdrojových kódů CVS.Repositorio CVS del 
     *  código fuente.CVS Quellcode-Versionierungssystem.ソースコードのCVSのリポジトリDépôt CVS 
     *  du code source.</p>
     */
    public static final Resource CVSRepository = m_model.createResource( "http://usefulinc.com/ns/doap#CVSRepository" );
    
    /** <p>Dépôt darcs du code source.ソースコードのdarcsのリポジトリdarcs source code repository.Repositorio 
     *  darcs del código fuente.</p>
     */
    public static final Resource DarcsRepository = m_model.createResource( "http://usefulinc.com/ns/doap#DarcsRepository" );
    
    /** <p>Repositorio Git del código fuente.Úložiště zdrojových kódů Git.Dépôt Git du 
     *  code source.Git source code repository.ソースコードのGitのリポジトリGit Quellcode-Versionierungssystem.</p>
     */
    public static final Resource GitRepository = m_model.createResource( "http://usefulinc.com/ns/doap#GitRepository" );
    
    /** <p>Mercurial source code repository.ソースコードのMercurialのリポジトリ</p> */
    public static final Resource HgRepository = m_model.createResource( "http://usefulinc.com/ns/doap#HgRepository" );
    
    /** <p>プログラミングのプロジェクトEin Projekt.Projekt.A project.Un proyecto.Un projet.</p> */
    public static final Resource Project = m_model.createResource( "http://usefulinc.com/ns/doap#Project" );
    
    /** <p>Úložiště zdrojových kódů.Quellcode-Versionierungssystem.Dépôt du code source.Source 
     *  code repository.ソースコードのリポジトリRepositorio del código fuente.</p>
     */
    public static final Resource Repository = m_model.createResource( "http://usefulinc.com/ns/doap#Repository" );
    
    /** <p>Dépôt Subversion du code source.Úložiště zdrojových kódů Subversion.ソースコードのSubversionのリポジトリSubversion 
     *  Quellcode-Versionierungssystem.Subversion source code repository.Repositorio 
     *  Subversion del código fuente.</p>
     */
    public static final Resource SVNRepository = m_model.createResource( "http://usefulinc.com/ns/doap#SVNRepository" );
    
    /** <p>あるシステムの詳しく書いた明細書。多分技術的なもの。A specification of a system's aspects, technical 
     *  or otherwise.</p>
     */
    public static final Resource Specification = m_model.createResource( "http://usefulinc.com/ns/doap#Specification" );
    
    /** <p>Versionsinformation eines Projekt Releases.Informace o uvolněné verzi projektu.リリースのバーション情報Détails 
     *  sur une version d'une realease d'un projet.Información sobre la versión de 
     *  un release del proyecto.Version information of a project release.</p>
     */
    public static final Resource Version = m_model.createResource( "http://usefulinc.com/ns/doap#Version" );
    
}
