/* CVS $UkId: $ */
package com.epimorphics.govData.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://purl.org/vocab/frbr/core 
 * @author Auto-generated by schemagen on 17 Jan 2010 18:15 
 */
public class FRBR {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/vocab/frbr/core#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property abridgement = m_model.createProperty( "http://purl.org/vocab/frbr/core#abridgement" );
    
    public static final Property abridgementOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#abridgementOf" );
    
    public static final Property adaption = m_model.createProperty( "http://purl.org/vocab/frbr/core#adaption" );
    
    public static final Property adaptionOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#adaptionOf" );
    
    public static final Property alternate = m_model.createProperty( "http://purl.org/vocab/frbr/core#alternate" );
    
    public static final Property alternateOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#alternateOf" );
    
    public static final Property arrangement = m_model.createProperty( "http://purl.org/vocab/frbr/core#arrangement" );
    
    public static final Property arrangementOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#arrangementOf" );
    
    public static final Property complement = m_model.createProperty( "http://purl.org/vocab/frbr/core#complement" );
    
    public static final Property complementOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#complementOf" );
    
    public static final Property creator = m_model.createProperty( "http://purl.org/vocab/frbr/core#creator" );
    
    public static final Property creatorOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#creatorOf" );
    
    public static final Property embodiment = m_model.createProperty( "http://purl.org/vocab/frbr/core#embodiment" );
    
    public static final Property embodimentOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#embodimentOf" );
    
    public static final Property exemplar = m_model.createProperty( "http://purl.org/vocab/frbr/core#exemplar" );
    
    public static final Property exemplarOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#exemplarOf" );
    
    public static final Property imitation = m_model.createProperty( "http://purl.org/vocab/frbr/core#imitation" );
    
    public static final Property imitationOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#imitationOf" );
    
    public static final Property owner = m_model.createProperty( "http://purl.org/vocab/frbr/core#owner" );
    
    public static final Property ownerOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#ownerOf" );
    
    public static final Property part = m_model.createProperty( "http://purl.org/vocab/frbr/core#part" );
    
    public static final Property partOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#partOf" );
    
    public static final Property producer = m_model.createProperty( "http://purl.org/vocab/frbr/core#producer" );
    
    public static final Property producerOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#producerOf" );
    
    public static final Property realization = m_model.createProperty( "http://purl.org/vocab/frbr/core#realization" );
    
    public static final Property realizationOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#realizationOf" );
    
    public static final Property realizer = m_model.createProperty( "http://purl.org/vocab/frbr/core#realizer" );
    
    public static final Property realizerOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#realizerOf" );
    
    public static final Property reconfiguration = m_model.createProperty( "http://purl.org/vocab/frbr/core#reconfiguration" );
    
    public static final Property reconfigurationOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#reconfigurationOf" );
    
    public static final Property relatedEndeavour = m_model.createProperty( "http://purl.org/vocab/frbr/core#relatedEndeavour" );
    
    public static final Property reproduction = m_model.createProperty( "http://purl.org/vocab/frbr/core#reproduction" );
    
    public static final Property reproductionOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#reproductionOf" );
    
    public static final Property responsibleEntity = m_model.createProperty( "http://purl.org/vocab/frbr/core#responsibleEntity" );
    
    public static final Property responsibleEntityOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#responsibleEntityOf" );
    
    public static final Property revision = m_model.createProperty( "http://purl.org/vocab/frbr/core#revision" );
    
    public static final Property revisionOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#revisionOf" );
    
    public static final Property subject = m_model.createProperty( "http://purl.org/vocab/frbr/core#subject" );
    
    public static final Property successor = m_model.createProperty( "http://purl.org/vocab/frbr/core#successor" );
    
    public static final Property successorOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#successorOf" );
    
    public static final Property summarization = m_model.createProperty( "http://purl.org/vocab/frbr/core#summarization" );
    
    public static final Property summarizationOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#summarizationOf" );
    
    public static final Property supplement = m_model.createProperty( "http://purl.org/vocab/frbr/core#supplement" );
    
    public static final Property supplementOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#supplementOf" );
    
    public static final Property transformation = m_model.createProperty( "http://purl.org/vocab/frbr/core#transformation" );
    
    public static final Property transformationOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#transformationOf" );
    
    public static final Property translation = m_model.createProperty( "http://purl.org/vocab/frbr/core#translation" );
    
    public static final Property translationOf = m_model.createProperty( "http://purl.org/vocab/frbr/core#translationOf" );
    
    public static final Resource ClassicalWork = m_model.createResource( "http://purl.org/vocab/frbr/core#ClassicalWork" );
    
    /** <p>This class corresponds to the FRBR group three entity 'Concept'.</p> */
    public static final Resource Concept = m_model.createResource( "http://purl.org/vocab/frbr/core#Concept" );
    
    /** <p>This class corresponds to the FRBR group two entity 'Corporate Body'.</p> */
    public static final Resource CorporateBody = m_model.createResource( "http://purl.org/vocab/frbr/core#CorporateBody" );
    
    public static final Resource Data = m_model.createResource( "http://purl.org/vocab/frbr/core#Data" );
    
    /** <p>This class represents any one of the FRBR group one entities.</p> */
    public static final Resource Endeavour = m_model.createResource( "http://purl.org/vocab/frbr/core#Endeavour" );
    
    /** <p>This class corresponds to the FRBR group three entity 'Event'.</p> */
    public static final Resource Event = m_model.createResource( "http://purl.org/vocab/frbr/core#Event" );
    
    /** <p>This class corresponds to the FRBR group one entity 'Expression'.</p> */
    public static final Resource Expression = m_model.createResource( "http://purl.org/vocab/frbr/core#Expression" );
    
    public static final Resource Image = m_model.createResource( "http://purl.org/vocab/frbr/core#Image" );
    
    /** <p>This class corresponds to the FRBR group one entity 'Item'.</p> */
    public static final Resource Item = m_model.createResource( "http://purl.org/vocab/frbr/core#Item" );
    
    public static final Resource LegalWork = m_model.createResource( "http://purl.org/vocab/frbr/core#LegalWork" );
    
    public static final Resource LiteraryWork = m_model.createResource( "http://purl.org/vocab/frbr/core#LiteraryWork" );
    
    /** <p>This class corresponds to the FRBR group one entity 'Manifestation'.</p> */
    public static final Resource Manifestation = m_model.createResource( "http://purl.org/vocab/frbr/core#Manifestation" );
    
    public static final Resource MovingImage = m_model.createResource( "http://purl.org/vocab/frbr/core#MovingImage" );
    
    /** <p>This class corresponds to the FRBR group three entity 'Object'.</p> */
    public static final Resource Object = m_model.createResource( "http://purl.org/vocab/frbr/core#Object" );
    
    public static final Resource Performance = m_model.createResource( "http://purl.org/vocab/frbr/core#Performance" );
    
    /** <p>This class corresponds to the FRBR group two entity 'Person'.</p> */
    public static final Resource Person = m_model.createResource( "http://purl.org/vocab/frbr/core#Person" );
    
    /** <p>This class corresponds to the FRBR group three entity 'Place'.</p> */
    public static final Resource Place = m_model.createResource( "http://purl.org/vocab/frbr/core#Place" );
    
    /** <p>This class represents any of the FRBR group two entities.</p> */
    public static final Resource ResponsibleEntity = m_model.createResource( "http://purl.org/vocab/frbr/core#ResponsibleEntity" );
    
    public static final Resource ScholarlyWork = m_model.createResource( "http://purl.org/vocab/frbr/core#ScholarlyWork" );
    
    public static final Resource Sound = m_model.createResource( "http://purl.org/vocab/frbr/core#Sound" );
    
    /** <p>This class represents any of the FRBR group three entities.</p> */
    public static final Resource Subject = m_model.createResource( "http://purl.org/vocab/frbr/core#Subject" );
    
    public static final Resource Text = m_model.createResource( "http://purl.org/vocab/frbr/core#Text" );
    
    /** <p>This class corresponds to the FRBR group one entity 'Work'.</p> */
    public static final Resource Work = m_model.createResource( "http://purl.org/vocab/frbr/core#Work" );
    
    public static final Resource me = m_model.createResource( "http://bruce.darcus.name/about#me" );
    
    public static final Resource me_INSTANCE = m_model.createResource( "http://iandavis.com/id/me" );
    
}
