/* CVS $Id: $ */
package com.epimorphics.govData.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from ../../../../../resources/vocabulary/geography.ttl 
 * @author Auto-generated by schemagen on 04 Jun 2010 12:07 
 */
public class GEOGRAPHY {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://statistics.data.gov.uk/def/geography/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property coverage = m_model.createProperty( "http://statistics.data.gov.uk/def/geography/coverage" );
    
    public static final Property educationAndLearningWalesRegion = m_model.createProperty( "http://statistics.data.gov.uk/def/geography/educationAndLearningWalesRegion" );
    
    public static final Property educationAndLearningWalesRegionalOffice = m_model.createProperty( "http://statistics.data.gov.uk/def/geography/educationAndLearningWalesRegionalOffice" );
    
    public static final Property educationAndLibraryBoard = m_model.createProperty( "http://statistics.data.gov.uk/def/geography/educationAndLibraryBoard" );
    
    public static final Property educationAndLibraryBoardArea = m_model.createProperty( "http://statistics.data.gov.uk/def/geography/educationAndLibraryBoardArea" );
    
    public static final Property localEducationAuthority = m_model.createProperty( "http://statistics.data.gov.uk/def/geography/localEducationAuthority" );
    
    public static final Property localEducationAuthorityArea = m_model.createProperty( "http://statistics.data.gov.uk/def/geography/localEducationAuthorityArea" );
    
    /** <p>The body responsible for local education for an area. For England and Wales, 
     *  this is a Local Education Authority. For Scotland, it's a local authority. 
     *  For Wales it's an Education and Library Board.</p>
     */
    public static final Property localEducationBody = m_model.createProperty( "http://statistics.data.gov.uk/def/geography/localEducationBody" );
    
    public static final Property localLearningAndSkillsCouncil = m_model.createProperty( "http://statistics.data.gov.uk/def/geography/localLearningAndSkillsCouncil" );
    
    public static final Property localLearningAndSkillsCouncilArea = m_model.createProperty( "http://statistics.data.gov.uk/def/geography/localLearningAndSkillsCouncilArea" );
    
    /** <p>The ELWa regions have the same boundaries as the former Training Enterprise 
     *  Councils.</p>
     */
    public static final Resource EducationAndLearningWalesRegion = m_model.createResource( "http://statistics.data.gov.uk/def/geography/EducationAndLearningWalesRegion" );
    
    /** <p>Education and Learning Wales (ELWa) is responsible for funding and planning 
     *  post-16 education and training in Wales. This organisation was established 
     *  in April 2001 as a replacement for the Training Enterprise Councils (although 
     *  it also took on other responsibilities) and its aim is to increase the standards 
     *  and range of learning opportunities for businesses, communities and the individual. 
     *  ELWa has 4 regional offices.</p>
     */
    public static final Resource EducationAndLearningWalesRegionalOffice = m_model.createResource( "http://statistics.data.gov.uk/def/geography/EducationAndLearningWalesRegionalOffice" );
    
    /** <p>Northern Ireland does not have LEAs; instead, local education administration 
     *  is carried out by five Education and Library Boards (Belfast, North Eastern, 
     *  South Eastern, Southern and Western), which consist of contiguous groupings 
     *  of district council areas.</p>
     */
    public static final Resource EducationAndLibraryBoard = m_model.createResource( "http://statistics.data.gov.uk/def/geography/EducationAndLibraryBoard" );
    
    /** <p>The area covered by an Education and Library Board.</p> */
    public static final Resource EducationAndLibraryBoardArea = m_model.createResource( "http://statistics.data.gov.uk/def/geography/EducationAndLibraryBoardArea" );
    
    /** <p>LEAs are the bodies responsible for the local administration of state sector 
     *  education services in England and Wales. Each LEA coincides with a county, 
     *  unitary authority, metropolitan district or London borough. LEA boundaries 
     *  are adjusted annually to correspond with any changes to the boundaries of 
     *  these areas.</p>
     */
    public static final Resource LocalEducationAuthority = m_model.createResource( "http://statistics.data.gov.uk/def/geography/LocalEducationAuthority" );
    
    /** <p>The area covered by a local education authority.</p> */
    public static final Resource LocalEducationAuthorityArea = m_model.createResource( "http://statistics.data.gov.uk/def/geography/LocalEducationAuthorityArea" );
    
    /** <p>The Learning and Skills Council (LSC) is responsible for funding and planning 
     *  post-16 education and training in England. This organisation was established 
     *  in April 2001 as a replacement for the Training Enterprise Councils (although 
     *  they also took on other responsibilities) and its aim is to increase the standards 
     *  and range of learning opportunities for businesses, communities and the individual. 
     *  The LSC has 47 local offices known as Local Learning and Skills Councils (LLSCs).</p>
     */
    public static final Resource LocalLearningAndSkillsCouncil = m_model.createResource( "http://statistics.data.gov.uk/def/geography/LocalLearningAndSkillsCouncil" );
    
    /** <p>LLSCs are based on local authority boundaries. In practice, these result in 
     *  a variety of constitutions, including single counties; county / unitary authority 
     *  groupings; and groupings of unitary authorities, metropolitan districts or 
     *  London boroughs.</p>
     */
    public static final Resource LocalLearningAndSkillsCouncilArea = m_model.createResource( "http://statistics.data.gov.uk/def/geography/LocalLearningAndSkillsCouncilArea" );
    
}
