/* CVS $Id: $ */
package com.epimorphics.govData.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from ../../../../../resources/vocabulary/administrative-geography.ttl 
 * @author Auto-generated by schemagen on 04 Jun 2010 13:14 
 */
public class ONSADMINGEOGRAPHY {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://statistics.data.gov.uk/def/administrative-geography/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final OntProperty country = m_model.createOntProperty( "http://statistics.data.gov.uk/def/administrative-geography/country" );
    
    public static final OntProperty county = m_model.createOntProperty( "http://statistics.data.gov.uk/def/administrative-geography/county" );
    
    public static final OntProperty coverage = m_model.createOntProperty( "http://statistics.data.gov.uk/def/administrative-geography/coverage" );
    
    public static final OntProperty district = m_model.createOntProperty( "http://statistics.data.gov.uk/def/administrative-geography/district" );
    
    public static final OntProperty localAuthority = m_model.createOntProperty( "http://statistics.data.gov.uk/def/administrative-geography/localAuthority" );
    
    public static final OntProperty region = m_model.createOntProperty( "http://statistics.data.gov.uk/def/administrative-geography/region" );
    
    public static final OntClass Country = m_model.createClass( "http://statistics.data.gov.uk/def/administrative-geography/Country" );
    
    /** <p>Includes old-style metropolitan counties as well as new-style non-metropolitan 
     *  counties.</p>
     */
    public static final OntClass County = m_model.createClass( "http://statistics.data.gov.uk/def/administrative-geography/County" );
    
    /** <p>Councils of various kinds, including both county and district councils.</p> */
    public static final OntClass LocalAuthority = m_model.createClass( "http://statistics.data.gov.uk/def/administrative-geography/LocalAuthority" );
    
    /** <p>Areas that are covered by different types of local authority. These may be 
     *  counties or local authority districts of various kinds (including unitary 
     *  authorities and london boroughs).</p>
     */
    public static final OntClass LocalAuthorityArea = m_model.createClass( "http://statistics.data.gov.uk/def/administrative-geography/LocalAuthorityArea" );
    
    /** <p>A superclass for areas that have local authorities, such as metropolitan and 
     *  non-metropolitan districts, unitary authorities and London boroughs.</p>
     */
    public static final OntClass LocalAuthorityDistrict = m_model.createClass( "http://statistics.data.gov.uk/def/administrative-geography/LocalAuthorityDistrict" );
    
    public static final OntClass MetropolitanCounty = m_model.createClass( "http://statistics.data.gov.uk/def/administrative-geography/MetropolitanCounty" );
    
    public static final OntClass NonMetropolitanCounty = m_model.createClass( "http://statistics.data.gov.uk/def/administrative-geography/NonMetropolitanCounty" );
    
}
