/* CVS $Id: $ */
package com.epimorphics.govData.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from ../../../../../resources/vocabulary/electoral-geography.ttl 
 * @author Auto-generated by schemagen on 04 Jun 2010 12:09 
 */
public class ONSELECTORALGEOGRAPHY {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://statistics.data.gov.uk/def/electoral-geography/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property constituency = m_model.createProperty( "http://statistics.data.gov.uk/def/electoral-geography/constituency" );
    
    public static final Property parliamentaryConstituency = m_model.createProperty( "http://statistics.data.gov.uk/def/electoral-geography/parliamentaryConstituency" );
    
    public static final Property region = m_model.createProperty( "http://statistics.data.gov.uk/def/electoral-geography/region" );
    
    public static final Property ward = m_model.createProperty( "http://statistics.data.gov.uk/def/electoral-geography/ward" );
    
}
