/* CVS $UkId: $ */
package com.epimorphics.govData.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from http://purl.org/net/provenance/ns 
 * @author Auto-generated by schemagen on 18 Feb 2010 09:45 
 */
public class PROVENANCE {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/net/provenance/ns#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>This property refers to the service that provided the Web representation during 
     *  the execution of a data access.</p>
     */
    public static final ObjectProperty accessedService = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#accessedService" );
    
    /** <p>This property refers to an artifact that contained a data item. This artifact 
     *  can either be a Web representation of the data item (see class &lt;a xmlns="http://www.w3.org/1999/xhtml" 
     *  href="#Representation" xml:lang="en"&gt;prv:Representation&lt;/a&gt;) or it 
     *  can be another data item of a larger granularity (e.g. an RDF statement is 
     *  usually contained in an RDF graph).</p>
     */
    public static final ObjectProperty containedBy = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#containedBy" );
    
    /** <p>This property refers to the creation of a data item.</p> */
    public static final ObjectProperty createdBy = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#createdBy" );
    
    /** <p>This is an abstract property that refers to an artifact which was used during 
     *  an execution.</p>
     */
    public static final ObjectProperty employedArtifact = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#employedArtifact" );
    
    /** <p>This property refers to a file that contained a data item.</p> */
    public static final ObjectProperty encodedBy = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#encodedBy" );
    
    /** <p>This is an abstract property that refers to an actor involved in an execution.</p> */
    public static final ObjectProperty involvedActor = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#involvedActor" );
    
    /** <p>This property refers to a human actor who was operating a non-human actor. 
     *  For instance, a service provider operates a data providing service (see class 
     *  &lt;a xmlns="http://www.w3.org/1999/xhtml" href="#DataProvidingService" xml:lang="en"&gt;prv:DataProvidingService&lt;/a&gt;). 
     *  Another example is a human actor who operates a non-human data creating actor.</p>
     */
    public static final ObjectProperty operatedBy = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#operatedBy" );
    
    /** <p>This property refers to an actor that/who performed an execution.</p> */
    public static final ObjectProperty performedBy = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#performedBy" );
    
    /** <p>This property refers to an immediately preceding version of a data item; hence, 
     *  the new version (i.e. the subject) has been created using the old version 
     *  (i.e. the object). We strongly encourage to also describe this creation of 
     *  the new version explicitly.</p>
     */
    public static final ObjectProperty precededBy = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#precededBy" );
    
    /** <p>This property refers to the data access by which a Web representation of a 
     *  data item has been retrieved from the Web.</p>
     */
    public static final ObjectProperty retrievedBy = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#retrievedBy" );
    
    /** <p>This property refers to a data publisher who used a data providing services.</p> */
    public static final ObjectProperty usedBy = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#usedBy" );
    
    /** <p>This property refers to a source data item that has been used during the creation 
     *  of a data item. Examples for source data are the content of a document used 
     *  for machine learning, the statements in a knowledge base used to entail a 
     *  new statement, and the entries in a database used to answer a query. Notice, 
     *  all source data has provenance; we strongly encourage to describe this provenance 
     *  as well, at least as far as available information permits.</p>
     */
    public static final ObjectProperty usedData = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#usedData" );
    
    /** <p>This property refers to a file encoding the source data item that has been 
     *  used during the creation of a data item. Notice, all files that encode source 
     *  data have provenance; we strongly encourage to describe this provenance as 
     *  well, at least as far as available information permits.</p>
     */
    public static final ObjectProperty usedFile = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#usedFile" );
    
    /** <p>This property refers to a creation guideline which guided the execution of 
     *  a data creation. Examples for creation guidelines are transformation rules, 
     *  mapping definitions, entailment rules, and database queries. Notice, all creation 
     *  guidelines have provenance; we strongly encourage to describe this provenance 
     *  as well, at least as far as available information permits.</p>
     */
    public static final ObjectProperty usedGuideline = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#usedGuideline" );
    
    /** <p>This property refers to a file encoding a creation guideline which guided 
     *  the execution of a data creation. Notice, all files encoding creation guidelines 
     *  have provenance; we strongly encourage to describe this provenance as well, 
     *  at least as far as available information permits.</p>
     */
    public static final ObjectProperty usedGuidelineFile = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#usedGuidelineFile" );
    
    /** <p>This is an abstract property that refers to the execution by which an artifact 
     *  was yielded.</p>
     */
    public static final ObjectProperty yieldedBy = m_model.createObjectProperty( "http://purl.org/net/provenance/ns#yieldedBy" );
    
    /** <p>This property refers to the time an execution has been performed at.</p> */
    public static final DatatypeProperty performedAt = m_model.createDatatypeProperty( "http://purl.org/net/provenance/ns#performedAt" );
    
    /** <p>Actor is a general class that represents actors which usually performed the 
     *  execution (see the class &lt;a xmlns="http://www.w3.org/1999/xhtml" href="#Execution" 
     *  xml:lang="en"&gt;Execution&lt;/a&gt;) of an action or a process.</p>
     */
    public static final OntClass Actor = m_model.createClass( "http://purl.org/net/provenance/ns#Actor" );
    
    /** <p>Artifact is a general class that represents artifacts which can be used during 
     *  the execution (see the class &lt;a xmlns="http://www.w3.org/1999/xhtml" href="#Execution" 
     *  xml:lang="en"&gt;Execution&lt;/a&gt;) of an action or a process and which 
     *  can also be the result of such an execution.</p>
     */
    public static final OntClass Artifact = m_model.createClass( "http://purl.org/net/provenance/ns#Artifact" );
    
    /** <p>CreationGuideline is a class that represents a guideline used to guide the 
     *  execution of a data creation. Examples for creation guidelines are transformation 
     *  rules, mapping definitions, entailment rules, and database queries.</p>
     */
    public static final OntClass CreationGuideline = m_model.createClass( "http://purl.org/net/provenance/ns#CreationGuideline" );
    
    /** <p>DataAccess is a class that represents the completed execution of accessing 
     *  a data item on the Web.</p>
     */
    public static final OntClass DataAccess = m_model.createClass( "http://purl.org/net/provenance/ns#DataAccess" );
    
    /** <p>DataCreation is a class that represents the completed creation of a data item.</p> */
    public static final OntClass DataCreation = m_model.createClass( "http://purl.org/net/provenance/ns#DataCreation" );
    
    /** <p>DataItem is a general class that represents data items of any kind.</p> */
    public static final OntClass DataItem = m_model.createClass( "http://purl.org/net/provenance/ns#DataItem" );
    
    /** <p>DataProvidingService is a class that represents a non-human actor - usually 
     *  a Web service or a server - that processes data access requests and actually 
     *  sends the requested Web representations (i.e. &lt;a xmlns="http://www.w3.org/1999/xhtml" 
     *  href="#Representation" xml:lang="en"&gt;prv:Representation&lt;/a&gt;) over 
     *  the Web.</p>
     */
    public static final OntClass DataProvidingService = m_model.createClass( "http://purl.org/net/provenance/ns#DataProvidingService" );
    
    /** <p>DataPublisher is a class that represents entities such as persons, groups, 
     *  or organizations who use a data providing service (see class &lt;a xmlns="http://www.w3.org/1999/xhtml" 
     *  href="#DataProvidingService" xml:lang="en"&gt;prv:DataProvidingService&lt;/a&gt;) 
     *  to publish data on the Web.</p>
     */
    public static final OntClass DataPublisher = m_model.createClass( "http://purl.org/net/provenance/ns#DataPublisher" );
    
    /** <p>This class is deprecated and will be removed from the Provenance Vocabulary 
     *  shortly. Use &lt;a xmlns="http://www.w3.org/1999/xhtml" href="#Representation" 
     *  xml:lang="en"&gt;prv:Representation&lt;/a&gt; instead. prv:Document was deprecated 
     *  because its name caused confusion; the name made people assume this class 
     *  represents information resources which is not the case; in fact, it represents 
     *  a Web representation of an information resource.</p>
     */
    public static final OntClass Document = m_model.createClass( "http://purl.org/net/provenance/ns#Document" );
    
    /** <p>Execution is a general class that represents completed executions of actions 
     *  or processes. An execution is usually performed by an actor (see the class 
     *  &lt;a xmlns="http://www.w3.org/1999/xhtml" href="#Actor" xml:lang="en"&gt;Actor&lt;/a&gt;) 
     *  and an execution, in most cases, yielded an artifact (see the class &lt;a 
     *  xmlns="http://www.w3.org/1999/xhtml" href="#Artifact" xml:lang="en"&gt;Artifact&lt;/a&gt;).</p>
     */
    public static final OntClass Execution = m_model.createClass( "http://purl.org/net/provenance/ns#Execution" );
    
    /** <p>File is a general class that represents files/documents of any kind.</p> */
    public static final OntClass File = m_model.createClass( "http://purl.org/net/provenance/ns#File" );
    
    /** <p>HumanActor is a general class that represents actors who are social beings 
     *  such as persons, organizations, companies.</p>
     */
    public static final OntClass HumanActor = m_model.createClass( "http://purl.org/net/provenance/ns#HumanActor" );
    
    /** <p>NonHumanActor is a general class that represents actors who are not social 
     *  beings.</p>
     */
    public static final OntClass NonHumanActor = m_model.createClass( "http://purl.org/net/provenance/ns#NonHumanActor" );
    
    /** <p>Representation is a general concept that represents a Web representation of 
     *  an information resource such as a data item. Such a Web representation was 
     *  used during the retrieval of a data item from the Web.</p>
     */
    public static final OntClass Representation = m_model.createClass( "http://purl.org/net/provenance/ns#Representation" );
    
    public static final Individual olaf = m_model.createIndividual( "http://olafhartig.de/foaf.rdf#olaf", m_model.createClass( "http://xmlns.com/foaf/0.1/Person" ) );
    
    public static final Individual __ = m_model.createIndividual( "http://purl.org/net/provenance/ns#", m_model.createClass( "http://www.w3.org/2002/07/owl#Ontology" ) );
    
    public static final Individual me = m_model.createIndividual( "http://users.ox.ac.uk/~zool0770/foaf.rdf#me", m_model.createClass( "http://xmlns.com/foaf/0.1/Person" ) );
    
}
